<a href="https://colab.research.google.com/github/AriyaArKa/2-2-Labs/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

list vs numpy

In [2]:
from time import process_time

time taken by list

In [7]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0005281749999994645


In [8]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00019710699999997416


Numpy Arrays

In [9]:
#list
list1 = [1,2,3,4,5,6]
print(list1)
type(list1)

[1, 2, 3, 4, 5, 6]


list

In [10]:
np_array = np.array([1,2,3,4,5,6])
print(np_array)
type(np_array)

[1 2 3 4 5 6]


numpy.ndarray

In [11]:
#creating 1 dim array
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
a.shape

(4,)

In [14]:
#creating 2 dim array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
b.shape

(2, 4)

In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [17]:
c.shape

(2, 4)

initial placeholder in umpy arrays

In [18]:
#array of zeros
x = np.zeros((4,5))
print(x)

#array of ones
y=np.ones((3,3))
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#array of perticlar values
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:
#idenetity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
